### ISSUE TITLE
losing connection bug

### ISSUE THREAD

**Issue by Hecarimdeveloper** [phanxgames/AetherStory#59]
when connection is lost in case of internet outage for example, the game will bug out and not allow me to close it or relog. I had to close it through task manager.

**Comment by phanxgames** [comment]
Thank you for reporting. Here is some details I found on my end:

```
0|phanxser | TypeError: Cannot read property 'request' of null
0|phanxser |     at Object.<anonymous> (/var/OneDrive/Development/nodejs/phanxserver/pxscript/Conversation.ts:36:51)
0|phanxser |     at Generator.next (<anonymous>)
0|phanxser |     at /var/nodejs/phanxserver/dist/pxscript/Conversation.js:7:71
0|phanxser |     at new Promise (<anonymous>)
0|phanxser |     at __awaiter (/var/nodejs/phanxserver/dist/pxscript/Conversation.js:3:12)
0|phanxser |     at Object.message (/var/nodejs/phanxserver/dist/pxscript/Conversation.js:34:16)
0|phanxser |     at result (evalmachine.<anonymous>:18:9)
0|phanxser |     at process._tickCallback (internal/process/next_tick.js:68:7)
```
